name: ai_classification

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install langchain-google-genai langchain-core pandas pydantic

     
      - name: category and level  classification
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python ai_agent.py
        
      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add linkedin_jobs.db
          git commit -m "Auto-update jobs" || exit 0
          git push
